# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

markdown: kramdown
timezone: Europe/Berlin
sass:
  style: compressed

# Site settings
baseurl: "" # the subpath of your site, e.g. /blog
url: http://www.ephigenia.de # the base hostname & protocol for your site
repository: Ephigenia/Ephigenia.github.io

# content settings
title: Marcel Eichner
email: marcel.eichner@ephigenia.de
description: >
  Website of Marcel Eichner, full-stack Javascript & PHP web developer from Berlin.

collections:
  projects:
    output: true
    permalink: /project/:path/

# profiles
twitter_username: ephigenia
github_username: Ephigenia
gitlab_username: ephigenia
xing_username: Marcel_Eichner
linkedin_username: ephigenia

# tracking
analytics:
  google:
    tracking_id: UA-80368234-1

# List of files & directories jekyll should not put into the _site directory
exclude:
  - CNAME
  - Gemfile
  - Gemfile.lock
  - Makefile
  - MIT-LICENSE
  - Procfile
  - Rakefile
  - README.md
